/**
 * Intentionally buggy Java code – generated by an LLM with common mistakes.
 *
 * Bugs introduced:
 *   1. Missing semicolon on line 12.
 *   2. Wrong return type: `reverse` returns int but should return String.
 *   3. NullPointerException risk: `getLength` does not guard against null input.
 *   4. Off-by-one in `isPalindrome` (uses <= instead of <).
 */
public class BuggyStringUtils {

    // Bug 1: missing semicolon
    public static int countVowels(String s) {
        int count = 0
        for (char c : s.toCharArray()) {
            if ("aeiouAEIOU".indexOf(c) >= 0) {
                count++;
            }
        }
        return count;
    }

    // Bug 2: return type mismatch – should be String
    public static int reverse(String s) {
        return new StringBuilder(s).reverse().toString();
    }

    // Bug 3: potential NullPointerException
    public static int getLength(String s) {
        return s.length();   // will throw NPE if s == null
    }

    // Bug 4: off-by-one in loop condition (uses i <= mid, should be i < mid)
    public static boolean isPalindrome(String s) {
        int n = s.length();
        int mid = n / 2;
        for (int i = 0; i <= mid; i++) {
            if (s.charAt(i) != s.charAt(n - 1 - i)) {
                return false;
            }
        }
        return true;
    }

    public static void main(String[] args) {
        System.out.println(countVowels("hello world"));
        System.out.println(reverse("abcde"));
        System.out.println(getLength("test"));
        System.out.println(isPalindrome("racecar"));
    }
}
