"""REST API - FastAPI application for the automated testing and debugging system."""

from __future__ import annotations

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from .bug_analyzer import BugReport, ErrorType, analyze_compilation_errors, analyze_runtime_errors
from .java_executor import compile_and_run, compile_java, run_java
from .llm_client import LLMConfig
from .pipeline import PipelineResult, run_pipeline
from .test_generator import generate_method_tests

app = FastAPI(
    title="Java Code Testing & Debugging API",
    description=(
        "Automated system for testing and debugging Java source code "
        "generated by Large Language Models."
    ),
    version="1.0.0",
)


# ---------- Request / Response models ----------

class CompileRequest(BaseModel):
    source_code: str = Field(..., description="Java source code to compile")


class RunRequest(BaseModel):
    source_code: str = Field(..., description="Java source code to compile and run")
    stdin_input: str = Field("", description="Standard input for the program")
    timeout: int = Field(10, ge=1, le=60, description="Execution timeout in seconds")


class TestCaseInput(BaseModel):
    input: str = Field("", description="stdin input for this test case")
    expected_output: str = Field("", description="Expected stdout")
    description: str = Field("", description="Test case description")


class PipelineRequest(BaseModel):
    source_code: str = Field(..., description="Java source code")
    test_cases: list[TestCaseInput] = Field(default_factory=list)
    stdin_input: str = Field("")
    expected_output: str = Field("")
    use_llm: bool = Field(False, description="Use LLM for analysis (requires API key)")
    timeout: int = Field(10, ge=1, le=60)


class AnalyzeRequest(BaseModel):
    source_code: str = Field(..., description="Java source code")
    error_output: str = Field("", description="Compiler or runtime error output")
    error_type: str = Field("compilation", description="'compilation' or 'runtime'")


class GenerateTestsRequest(BaseModel):
    source_code: str = Field(..., description="Java source code to generate tests for")


class BugReportResponse(BaseModel):
    error_type: str
    message: str
    line_number: int | None = None
    suggestion: str = ""


class CompileResponse(BaseModel):
    success: bool
    errors: str = ""
    class_name: str = ""


class RunResponse(BaseModel):
    compilation_success: bool
    compilation_errors: str = ""
    execution_success: bool | None = None
    stdout: str = ""
    stderr: str = ""
    return_code: int | None = None
    timed_out: bool = False


class PipelineResponse(BaseModel):
    source_code: str
    compilation_success: bool
    execution_success: bool | None = None
    stdout: str = ""
    stderr: str = ""
    bugs: list[BugReportResponse] = []
    test_results: list[dict] = []
    llm_analysis: str | None = None
    fixed_code: str | None = None
    stages_completed: list[str] = []


class AnalyzeResponse(BaseModel):
    bugs: list[BugReportResponse]


class GenerateTestsResponse(BaseModel):
    test_class_name: str
    test_source_code: str
    test_count: int


# ---------- Endpoints ----------

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "ok"}


@app.post("/compile", response_model=CompileResponse)
async def compile_endpoint(request: CompileRequest):
    """Compile Java source code and return the result."""
    result = compile_java(request.source_code)
    return CompileResponse(
        success=result.success,
        errors=result.errors,
        class_name=result.class_name,
    )


@app.post("/run", response_model=RunResponse)
async def run_endpoint(request: RunRequest):
    """Compile and run Java source code."""
    comp, exec_result = compile_and_run(
        request.source_code,
        request.stdin_input,
        request.timeout,
    )
    response = RunResponse(
        compilation_success=comp.success,
        compilation_errors=comp.errors,
    )
    if exec_result is not None:
        response.execution_success = exec_result.success
        response.stdout = exec_result.stdout
        response.stderr = exec_result.stderr
        response.return_code = exec_result.return_code
        response.timed_out = exec_result.timed_out
    return response


@app.post("/analyze", response_model=AnalyzeResponse)
async def analyze_endpoint(request: AnalyzeRequest):
    """Analyze error output and return bug reports with suggestions."""
    if request.error_type == "runtime":
        bugs = analyze_runtime_errors(request.error_output)
    else:
        bugs = analyze_compilation_errors(request.error_output)

    return AnalyzeResponse(
        bugs=[
            BugReportResponse(
                error_type=b.error_type.value,
                message=b.message,
                line_number=b.line_number,
                suggestion=b.suggestion,
            )
            for b in bugs
        ]
    )


@app.post("/generate-tests", response_model=GenerateTestsResponse)
async def generate_tests_endpoint(request: GenerateTestsRequest):
    """Generate JUnit test cases for the given Java source code."""
    suite = generate_method_tests(request.source_code)
    return GenerateTestsResponse(
        test_class_name=suite.class_name,
        test_source_code=suite.source_code,
        test_count=len(suite.test_cases),
    )


@app.post("/pipeline", response_model=PipelineResponse)
async def pipeline_endpoint(request: PipelineRequest):
    """Run the full testing and debugging pipeline."""
    tc_dicts = [tc.model_dump() for tc in request.test_cases] if request.test_cases else None

    result = await run_pipeline(
        source_code=request.source_code,
        test_cases=tc_dicts,
        stdin_input=request.stdin_input,
        expected_output=request.expected_output,
        use_llm=request.use_llm,
        timeout=request.timeout,
    )

    bugs_resp = [
        BugReportResponse(
            error_type=b.error_type.value,
            message=b.message,
            line_number=b.line_number,
            suggestion=b.suggestion,
        )
        for b in result.bugs
    ]

    return PipelineResponse(
        source_code=result.source_code,
        compilation_success=result.compilation.success if result.compilation else False,
        execution_success=result.execution.success if result.execution else None,
        stdout=result.execution.stdout if result.execution else "",
        stderr=result.execution.stderr if result.execution else "",
        bugs=bugs_resp,
        test_results=result.test_results,
        llm_analysis=result.llm_analysis.content if result.llm_analysis else None,
        fixed_code=result.fixed_code,
        stages_completed=[s.value for s in result.stages_completed],
    )
