"""
FastAPI REST API for the Automated Java Testing & Debugging System.
"""
from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api.routes import router

app = FastAPI(
    title="Automated Java Testing & Debugging System",
    description=(
        "A research system that automatically compiles, tests, and debugs "
        "Java source code generated by large language models."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)
